'use sanity'

import { describe, it } from 'mocha'
import { expect } from 'chai'
import { isWeatherResults } from '../../contracts/weather'

describe('Contracts: IsWeatherResults()', () => {
  const testCases: Array<[string, unknown, boolean]> = [
    ['empty', {}, true],
    ['array', [], false],
    ['null', null, false],
    ['undefined', undefined, false],
    ['number', 42, false],
    ['string', 'foo', false],
    ['boolean', false, false],
    ['object temp', { temp: {} }, false],
    ['array temp', { temp: [] }, false],
    ['null temp', { temp: null }, false],
    ['undefined temp', { temp: undefined }, true],
    ['string temp', { temp: 'foo' }, false],
    ['boolean temp', { temp: false }, false],
    ['number temp', { temp: 42 }, true],
    [
      'missing temp',
      {
        pressure: 0,
        humidity: 0,
        description: '',
        icon: '',
        sunrise: 0,
        sunset: 0,
      },
      true,
    ],
    ['object pressure', { pressure: {} }, false],
    ['array pressure', { pressure: [] }, false],
    ['null pressure', { pressure: null }, false],
    ['undefined pressure', { pressure: undefined }, true],
    ['string pressure', { pressure: 'foo' }, false],
    ['boolean pressure', { pressure: false }, false],
    ['number pressure', { pressure: 42 }, true],
    [
      'missing pressure',
      {
        temp: 0,
        humidity: 0,
        description: '',
        icon: '',
        sunrise: 0,
        sunset: 0,
      },
      true,
    ],
    ['object humidity', { humidity: {} }, false],
    ['array humidity', { humidity: [] }, false],
    ['null humidity', { humidity: null }, false],
    ['undefined humidity', { humidity: undefined }, true],
    ['string humidity', { humidity: 'foo' }, false],
    ['boolean humidity', { humidity: false }, false],
    ['number humidity', { humidity: 42 }, true],
    [
      'missing humidity',
      {
        temp: 0,
        pressure: 0,
        description: '',
        icon: '',
        sunrise: 0,
        sunset: 0,
      },
      true,
    ],
    ['object description', { description: {} }, false],
    ['array description', { description: [] }, false],
    ['null description', { description: null }, false],
    ['undefined description', { description: undefined }, true],
    ['string description', { description: 'foo' }, true],
    ['boolean description', { description: false }, false],
    ['number description', { description: 42 }, false],
    [
      'missing description',
      {
        temp: 0,
        pressure: 0,
        humidity: 0,
        icon: '',
        sunrise: 0,
        sunset: 0,
      },
      true,
    ],
    ['object icon', { icon: {} }, false],
    ['array icon', { icon: [] }, false],
    ['null icon', { icon: null }, false],
    ['undefined icon', { icon: undefined }, true],
    ['string icon', { icon: 'foo' }, true],
    ['boolean icon', { icon: false }, false],
    ['number icon', { icon: 42 }, false],
    [
      'missing icon',
      {
        temp: 0,
        pressure: 0,
        humidity: 0,
        description: '',
        sunrise: 0,
        sunset: 0,
      },
      true,
    ],
    ['object sunrise', { sunrise: {} }, false],
    ['array sunrise', { sunrise: [] }, false],
    ['null sunrise', { sunrise: null }, false],
    ['undefined sunrise', { sunrise: undefined }, true],
    ['string sunrise', { sunrise: 'foo' }, false],
    ['boolean sunrise', { sunrise: false }, false],
    ['number sunrise', { sunrise: 42 }, true],
    [
      'missing sunrise',
      {
        temp: 0,
        humidity: 0,
        pressure: 0,
        description: '',
        icon: '',
        sunset: 0,
      },
      true,
    ],
    ['object sunset', { sunset: {} }, false],
    ['array sunset', { sunset: [] }, false],
    ['null sunset', { sunset: null }, false],
    ['undefined sunset', { sunset: undefined }, true],
    ['string sunset', { sunset: 'foo' }, false],
    ['boolean sunset', { sunset: false }, false],
    ['number sunset', { sunset: 42 }, true],
    [
      'missing sunset',
      {
        temp: 0,
        humidity: 0,
        pressure: 0,
        description: '',
        icon: '',
        sunrise: 0,
      },
      true,
    ],
  ]
  testCases.forEach(([name, value, expected]) => {
    it(`should ${expected ? 'accept' : 'reject'} ${name} object`, () => {
      expect(isWeatherResults(value)).to.equal(expected)
    })
  })
})
