'use sanity'

import { expect } from 'chai'
import { Functions, Imports } from '#routes/apiFunctions'
import { StubToKnex } from '#testutils/TypeGuards'
import Sinon from 'sinon'

const sandbox = Sinon.createSandbox()

interface KnexStub {
  select: Sinon.SinonStub
  increment: Sinon.SinonStub
  update: Sinon.SinonStub
  whereIn: Sinon.SinonStub
  orWhere: Sinon.SinonStub
  where: Sinon.SinonStub
}
const makeKnexInstance = (): KnexStub => ({
  select: sandbox.stub().returnsThis(),
  increment: sandbox.stub().returnsThis(),
  update: sandbox.stub().returnsThis(),
  whereIn: sandbox.stub().resolves([]),
  orWhere: sandbox.stub().resolves([]),
  where: sandbox.stub().resolves([]),
})
describe('routes/apiFunctions function SetLatestPicture', () => {
  let knexStub = sandbox.stub()
  let knexFake = StubToKnex(knexStub)
  let getParentFoldersStub = sandbox.stub()
  beforeEach(() => {
    knexStub = sandbox.stub().callsFake(() => StubToKnex(makeKnexInstance()))
    knexFake = StubToKnex(knexStub)
    getParentFoldersStub = sandbox.stub(Imports, 'GetParentFolders').returns([])
  })
  afterEach(() => {
    sandbox.restore()
  })
  it('should call knex once when searching for picture in the pictures table', async () => {
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.callCount).to.equal(1)
  })
  it('should search for picture in the pictures table', async () => {
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.firstCall.args).to.deep.equal(['pictures'])
  })
  it('should call select once when searching pictures table', async () => {
    const instance = makeKnexInstance()
    knexStub.onFirstCall().returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.select.callCount).to.be.equal(1)
  })
  it('should select seen column from pictures table while searching', async () => {
    const instance = makeKnexInstance()
    knexStub.onFirstCall().returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.select.firstCall.args).to.deep.equal(['seen'])
  })
  it('should call where once when filtering pictures table while searching', async () => {
    const instance = makeKnexInstance()
    knexStub.onFirstCall().returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.where.callCount).to.be.equal(1)
  })
  it('should filter pictures table by provided path while searching', async () => {
    const instance = makeKnexInstance()
    knexStub.onFirstCall().returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.where.firstCall.args).to.deep.equal([{ path: '/foo/bar/image.pdf' }])
  })
  it('should resolve to null when path is not found', async () => {
    const instance = makeKnexInstance()
    knexStub.onFirstCall().returns(instance)
    instance.where.resolves([])
    const result = await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(result).to.equal(null)
  })
  it('should make no additional knex calls when picture not found', async () => {
    const instance = makeKnexInstance()
    knexStub.onFirstCall().returns(instance)
    instance.where.resolves([])
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.callCount).to.equal(1)
  })
  it('should call knex twice when seen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: true }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.callCount).to.equal(2)
  })
  it('should query folders to update when seen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: true }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.getCall(1).args).to.deep.equal(['folders'])
  })
  it('should call update once when seen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: true }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.update.callCount).to.equal(1)
  })
  it('should update current column to selected picture path when seen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: true }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.update.getCall(0).args).to.deep.equal([{ current: '/foo/bar/image.pdf' }])
  })
  it('should call where once on folders when seen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: true }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.where.callCount).to.equal(1)
  })
  it('should update by folder name when seen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: true }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.where.getCall(0).args).to.deep.equal([{ path: '/foo/bar/' }])
  })
  it('should call knex four times when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.callCount).to.equal(4)
  })
  it('should query folders to increment seen count when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.getCall(1).args).to.deep.equal(['folders'])
  })
  it('should call increment once when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.increment.callCount).to.equal(1)
  })
  it('should increment seen count when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.increment.getCall(0).args).to.deep.equal(['seenCount', 1])
  })
  it('should call GetPictureFolders once when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(getParentFoldersStub.callCount).to.equal(1)
  })
  it('should use GetPictureFolders to get parent folders when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(getParentFoldersStub.firstCall.args).to.deep.equal(['/foo/bar/image.pdf'])
  })
  it('should call whereIn once when filtering parent folders when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    getParentFoldersStub.returns('FOOBAR')
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.whereIn.callCount).to.equal(1)
  })
  it('should filter parent folders by path when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    getParentFoldersStub.returns('FOOBAR')
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.whereIn.getCall(0).args).to.deep.equal(['path', 'FOOBAR'])
  })
  it('should query pictures to set seen flag when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(2).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.getCall(2).args).to.deep.equal(['pictures'])
  })
  it('should call update once on pictures when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(2).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.update.callCount).to.equal(1)
  })
  it('should update pictures to set seen flag when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(2).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.update.getCall(0).args).to.deep.equal([{ seen: true }])
  })
  it('should call where once on pictures when setting seen flag', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(2).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.where.callCount).to.equal(1)
  })
  it('should select picture using path to set seen flag when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(2).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.where.getCall(0).args).to.deep.equal([{ path: '/foo/bar/image.pdf' }])
  })
  it('should query folders to update when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(3).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(knexStub.getCall(3).args).to.deep.equal(['folders'])
  })
  it('should call update once on folders when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(3).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.update.callCount).to.equal(1)
  })
  it('should update current column to selected picture path when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(3).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.update.getCall(0).args).to.deep.equal([{ current: '/foo/bar/image.pdf' }])
  })
  it('should call where once on folders when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(3).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.where.callCount).to.equal(1)
  })
  it('should update by folder name when unseen picture is found', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: false }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(3).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.where.getCall(0).args).to.deep.equal([{ path: '/foo/bar/' }])
  })
  it('should treat picture with undefined seen field as unseen and increment seenCount', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: undefined }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.increment.callCount).to.equal(1)
  })
  it('should treat picture with undefined seen field as unseen and mark seen', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: undefined }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(2).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.update.firstCall.args).to.deep.equal([{ seen: true }])
  })
  it('should treat picture with null seen field as unseen and increment seenCount', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: null }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(1).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.increment.callCount).to.equal(1)
  })
  it('should treat picture with null seen field as unseen and mark seen', async () => {
    const searcher = makeKnexInstance()
    searcher.where.resolves([{ seen: null }])
    knexStub.onCall(0).returns(searcher)
    const instance = makeKnexInstance()
    knexStub.onCall(2).returns(instance)
    await Functions.SetLatestPicture(knexFake, '/foo/bar/image.pdf')
    expect(instance.update.firstCall.args).to.deep.equal([{ seen: true }])
  })
})
